{  
    "settings":{  
        "number_of_shards":3,
        "number_of_replicas":2
    },
   "mappings":{  
       "review":{  
           "properties":{  
               "CourseId":{  
                   "type":"keyword"
               },
              "ReviewId":{  
                  "type":"keyword"
              },
              "UserId":{  
                   "type":"keyword"
              },
              "PostedByInstructor":{  
                  "type":"boolean"
               },
              "Description":{  
                  "type":"text",
                  "analyzer":"standard"
              },
              "Edited":{  
                  "type":"boolean"
              },

              "CommentedOn":{  
                  "type":"date",
                  "format":"yyyy-MM-dd"
              },
              "EditedOn":{  
                  "type":"date",
                  "format":"yyyy-MM-dd"
              }
           }
       }
   }
}