#cloudbuild.yaml
steps:
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=./frontend/course-hub-ui/.env.enc
  - --plaintext-file=./frontend/course-hub-ui/.env
  - --location=global
  - --keyring=course-hub-keyring
  - --key=course-hub-key
- name: 'docker/compose:1.19.0'
  args: ['build']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/spp200_frontend:latest', 'gcr.io/$PROJECT_ID/spp200_frontend:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/spp200_backend:latest', 'gcr.io/$PROJECT_ID/spp200_backend:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/spp200_frontend:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/spp200_backend:$COMMIT_SHA']