apiVersion: v1
kind: Service
metadata:
  labels: 
    name: frontend-service
  name: frontend-service
spec:
  type: LoadBalancer
  ports: 
    - port: 80
      targetPort: 80
      protocol: TCP
  selector: 
    name: course-hub