# serverless.yml

service: udacity-data

provider:
  name: aws
  runtime: python2.7
  stage: dev
  region: us-east-2

functions:
  udacityapi:
    handler: handler.fetch_records_udacity

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux